# Generated by Django 5.1 on 2024-09-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название места')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название материала упаковки')),
                ('moisture_protection', models.BooleanField(verbose_name='Влагозащита')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('details', models.TextField(verbose_name='Описание предмета')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('count', models.IntegerField(blank=True, verbose_name='Количество/Объём')),
                ('status', models.CharField(blank=True, choices=[('exist', 'Существует'), ('recycled', 'Переработано'), ('thrown', 'Выброшено')], max_length=15, verbose_name='Статус')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_items.categorymodel', verbose_name='Категория предмета')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_items.locationmodel', verbose_name='Место')),
            ],
        ),
        migrations.CreateModel(
            name='BoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Номер коробки/пакета')),
                ('width', models.IntegerField(verbose_name='Ширина бокса/пакета')),
                ('height', models.IntegerField(verbose_name='Высота бокса/пакета')),
                ('depth', models.IntegerField(default=0, verbose_name='Глубина бокса')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_items.materialboxmodel', verbose_name='Материал')),
            ],
        ),
    ]
