# Generated by Django 5.1 on 2024-09-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxmodel',
            name='details',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
