# Generated by Django 5.1 on 2024-09-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0002_boxmodel_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialboxmodel',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название материала упаковки'),
        ),
    ]
