# Generated by Django 5.1 on 2024-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0003_alter_materialboxmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
