# Generated by Django 5.1 on 2024-09-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0004_alter_itemmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='inventory_items/static/uploads', verbose_name='Фотография'),
        ),
    ]
