# Generated by Django 5.1 on 2024-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0008_alter_itemmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/&d', verbose_name='Фотография'),
        ),
    ]
