# Generated by Django 5.1 on 2024-09-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0009_alter_itemmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_items.boxmodel', verbose_name='Упаковка'),
        ),
    ]
