# Generated by Django 5.1 on 2024-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0010_itemmodel_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
