# Generated by Django 5.1 on 2024-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0011_alter_itemmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxmodel',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to="'uploads/box/%Y/%m/%d'", verbose_name='Фото'),
        ),
    ]
