# Generated by Django 5.1 on 2024-09-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0012_boxmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='box',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.PROTECT, to='inventory_items.boxmodel', verbose_name='Упаковка'),
            preserve_default=False,
        ),
    ]
