# Generated by Django 5.1 on 2024-09-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0015_alter_itemmodel_options_remove_itemmodel_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_items.locationmodel', verbose_name='Место/локация'),
        ),
    ]
