# Generated by Django 5.1 on 2024-09-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0016_alter_boxmodel_options_itemmodel_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_items.categorymodel', verbose_name='Категория предмета'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='count',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество/Объём'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('exist', 'Существует'), ('recycled', 'Переработано'), ('thrown', 'Выброшено')], default='exist', max_length=15, verbose_name='Статус'),
        ),
    ]
