# Generated by Django 5.1 on 2024-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_of_the_day', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigarettes',
            name='data',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Дата'),
        ),
    ]
