# Generated by Django 5.1 on 2024-09-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_of_the_day', '0002_alter_cigarettes_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigarettes',
            name='data',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
