# Generated by Django 5.1 on 2024-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_of_the_day', '0003_alter_cigarettes_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullUpsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('count', models.IntegerField(verbose_name='Количество подтягиваний')),
                ('number_of_approaches', models.IntegerField(default=0, unique=True, verbose_name='Подход')),
            ],
        ),
    ]
