# Generated by Django 5.1 on 2024-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_of_the_day', '0004_pullupsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullupsmodel',
            name='number_of_approaches',
            field=models.IntegerField(default=0, verbose_name='Подход'),
        ),
    ]
