# Generated by Django 5.1 on 2024-09-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphonemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='sandbox1.categorysmartmodel'),
        ),
    ]
